;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="VoiceFX",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Bitcrush",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Chorus",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Filter.Strong",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.LowPass",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Phaser",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.PitchShift",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Reverb",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.RingModulation",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.RingModulation.Robot",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Effect.Volume.+20",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Pack",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Pack.Alien",DevComment="")
+GameplayTagList=(Tag="VoiceFX.Pack.FullMute",DevComment="")

